import { ComparisonData } from './types';

/**
 * Comparison data for IM8 vs Leading Greens Powder
 */
export const COMPARISON_DATA: ComparisonData = {
  im8: {
    name: 'Daily Ultimate Essentials',
    image: '//im8health.com/cdn/shop/files/sachet-thumb.png?v=1761040601',
    imageWidth: 170,
    imageHeight: 225,
    brandColor: '#50000B',
    backgroundColor: '#F5EAEA',
  },
  competitor: {
    name: 'Leading Greens Powder',
    image: '//im8health.com/cdn/shop/files/179-_Converted_B_1.png?v=1730093105',
    imageWidth: 80,
    imageHeight: 121,
    brandColor: '#18332A',
    backgroundColor: 'rgba(29, 95, 78, 0.25)',
  },
  features: [
    {
      id: 1,
      im8Content: 'Superfoods, Greens, Fruits, Herbs',
      im8HasFeature: true,
      competitorContent: 'Superfoods, Greens, Fruits, Herbs',
      competitorHasFeature: true,
      isInitiallyVisible: true,
    },
    {
      id: 2,
      im8Content: 'Clinical Dosed B Vitamins',
      im8HasFeature: true,
      competitorContent: 'Clinical Dosed B Vitamins',
      competitorHasFeature: true,
      isInitiallyVisible: true,
    },
    {
      id: 3,
      im8Content: '30mcg Clinical Dosed Vitamin D3',
      im8HasFeature: true,
      competitorContent: 'No Vitamin D3',
      competitorHasFeature: false,
      isInitiallyVisible: true,
    },
    {
      id: 4,
      im8Content: '40mcg Clinical Dosed Vitamin K2',
      im8HasFeature: true,
      competitorContent: 'Vitamin K2 dosage not disclosed',
      competitorHasFeature: false,
      isInitiallyVisible: true,
    },
    {
      id: 5,
      im8Content: '100mg Clinical Dosed CoQ10',
      im8HasFeature: true,
      competitorContent: 'CoQ10 dosage not disclosed',
      competitorHasFeature: false,
      isInitiallyVisible: true,
    },
    {
      id: 6,
      im8Content: '1000mg Clinical Dosed MSM',
      im8HasFeature: true,
      competitorContent: 'No MSM',
      competitorHasFeature: false,
      isInitiallyVisible: true,
    },
    {
      id: 7,
      im8Content: { main: '3g Prebiotic fiber', detail: '(50% more)' },
      im8HasFeature: true,
      competitorContent: '2g Prebiotic fiber',
      competitorHasFeature: false,
      isInitiallyVisible: true,
    },
    {
      id: 8,
      im8Content: { main: '900mg Clinical Dosed Vitamin C', detail: '(114% more)' },
      im8HasFeature: true,
      competitorContent: '420mg Vitamin C',
      competitorHasFeature: false,
      isInitiallyVisible: true,
    },
    {
      id: 9,
      im8Content: { main: '4.2mg Clinical Dosed Riboflavin', detail: '(110% more)' },
      im8HasFeature: true,
      competitorContent: '2mg Riboflavin',
      competitorHasFeature: false,
      isInitiallyVisible: true,
    },
    {
      id: 10,
      im8Content: { main: '65mg Magnesium', detail: '(150% more)' },
      im8HasFeature: true,
      competitorContent: '26mg Magnesium',
      competitorHasFeature: false,
      isInitiallyVisible: true,
    },
    // Hidden items (shown after "See More" click)
    {
      id: 11,
      im8Content: { main: '70mcg Clinical Dosed Selenium', detail: '(250% more)' },
      im8HasFeature: true,
      competitorContent: '20mcg Selenium',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
    {
      id: 12,
      im8Content: { main: '100mcg Clinical Dosed Chromium', detail: '(300% more)' },
      im8HasFeature: true,
      competitorContent: '25mcg Chromium',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
    {
      id: 13,
      im8Content: { main: '1mg Clinical Dosed Copper', detail: '(413% more)' },
      im8HasFeature: true,
      competitorContent: '195mcg Copper',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
    {
      id: 14,
      im8Content: { main: '3mg Clinical Dosed Manganese', detail: '(650% more)' },
      im8HasFeature: true,
      competitorContent: '400mcg Manganese',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
    {
      id: 15,
      im8Content: '50mcg Clinical Dosed Molybdenum',
      im8HasFeature: true,
      competitorContent: 'No Molybdenum',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
    {
      id: 16,
      im8Content: '150mcg Clinical Dosed Iodine',
      im8HasFeature: true,
      competitorContent: 'No Iodine',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
    {
      id: 17,
      im8Content: { main: '10b CFU Probiotics', detail: 'B coagulans BC99®, B subtilis DE111®' },
      im8HasFeature: true,
      competitorContent: '7.2b CFU Probiotics',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
    {
      id: 18,
      im8Content: { main: 'Postbiotics', detail: 'FloraSMART® (25mg)' },
      im8HasFeature: true,
      competitorContent: 'No Postbiotics',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
    {
      id: 19,
      im8Content: 'Cell Rejuvenation Technology 8®',
      im8HasFeature: true,
      competitorContent: 'No Proprietary Technology',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
    {
      id: 20,
      im8Content: { main: 'Stevia-free', detail: '(Fermented Sugarcane Extract)' },
      im8HasFeature: true,
      competitorContent: 'Includes Stevia',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
    {
      id: 21,
      im8Content: { main: 'No Refrigeration', detail: 'Shelf-stable Probiotics' },
      im8HasFeature: true,
      competitorContent: 'Refrigeration Needed',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
    {
      id: 22,
      im8Content: { main: 'Branded Ingredients', detail: 'Quatrefolic®, AstaPure®, DE111®, Bacillus BC99®, VegD3™, FloraSmart™, Nutralga®, Astapure®' },
      im8HasFeature: true,
      competitorContent: 'None',
      competitorHasFeature: false,
      isInitiallyVisible: false,
    },
  ],
};
